### ISSUE TITLE
请问镜像是什么版本，我的休眠有点问题，想直接换你这个试试

### ISSUE THREAD

**Issue by guoamocker** [ZipperLi/T480s#1]

**Comment by guoamocker** [comment]
哦哦，看到了....11.4，我的是11.2.2,

**Comment by guoamocker** [comment]
尴尬，你这个efi，休眠好使了，触控板不好使了。。。

**Comment by ZipperLi** [comment]
不存在啊，我啥都是好的啊。你也是T480s？

**Comment by ZipperLi** [comment]
> 哦哦，看到了....11.4，我的是11.2.2,

我现在升级到最新的11.5.1了。

**Comment by guoamocker** [comment]
> > 哦哦，看到了....11.4，我的是11.2.2,
> 
> 我现在升级到最新的11.5.1了。

我是T480不带s
